### ISSUE TITLE
Feature request: transition to background on last indent in gradient mode

### ISSUE THREAD

**Issue by Manuel-S** [chingucoding/IndentRainbow#23]
Hi, I like using this extension but the hard switch of colors makes it uncomfortable on the eye, that is why I have set up my color scheme to transition from/into the background color on the most used level:
![image](https://user-images.githubusercontent.com/1771314/124257694-e6abe100-db2c-11eb-936c-f7b1d54b7fed.png)
If there was a setting that transitioned to and from fully transparent in the first and last color rendered, that would be very much appreciated.

**Comment by chingucoding** [comment]
So the idea is that the left most color would slowly fade out and the right most color for an indentation would also fade into the background, is that correct?

That seems like a good idea. If you would like to work on this, feel free to do so, not sure when exactly I will get back to this.

**Comment by chingucoding** [comment]
Sorry for the slight delay of approximately two years developing this. Version 1.3.0 was just released that allows fading the colors in and out when using alternating mode.
