### ISSUE TITLE
Visual Studio stopped responding for 55 seconds

### ISSUE THREAD

**Issue by maximilien-noal** [chingucoding/IndentRainbow#26]
Got this yesterday with a file hitting the 5K line count.

File is here :
https://github.com/maximilien-noal/WpfHexEditorControl/blob/feature/avaloniaui/Sources/AvaloniaHexEditorCore/HexEditor.axaml.cs

**Comment by maximilien-noal** [comment]
I'm using the default config.

I disabled all extension except IndentRainbow -> the problem didn't occur again.

I guess VS reported the wrong extension.

**Comment by chingucoding** [comment]
Alright, thank you! If the issue occurs again, feel free to reopen this issue.
