### ISSUE TITLE
Quality of Life suggestion

### ISSUE THREAD

**Issue by madmanmoe** [chingucoding/IndentRainbow#37]
Not a major issue, just a quality-of-life suggestion. 

Maybe I'm just too much a noobie in VS, but I didn't realize VS needed to restart for changes to take effect (eg: file specific indent sizes, rainbow behavior changes, etc.). If somewhere in the instructions or in the options window a '(VS restart required)' was mentioned, it would be cool.

**Comment by chingucoding** [comment]
Thank you for the suggestion, I'll look into whether we can simply display a text at the top or if we need to include it in the explanations.
