### ISSUE TITLE
Enhancement request: use red indentation color when wrong number of spaces used

### ISSUE THREAD

**Issue by mikgam** [chingucoding/IndentRainbow#7]
One of the functionality in the VS Code extension is to change the indentation color to red to signal that the line isn't following the right number of tabs/spaces.  

In VS Code, if you remove a tab, and put the wrong number of spaces in it's place, or just remove a space if you use spaces instead of tabs, it would change the indentation color to be red for that line.  

In this VS extension, it keeps the colors on the indentations before that are valid, but when the current indentation is missing the space, it displays with the default color. 

It would be nice to match the VS Code extensions behavior which I like, as it highlights there is an issue with the indentations.  

![Untitled](https://user-images.githubusercontent.com/8495255/59523351-09fc8880-8e9f-11e9-8244-c13fc68be437.png)

**Comment by chingucoding** [comment]
This feature is kinda a mixed bag since there are scenarios where it would not make sense to mark indentation as "wrong" (especially long lines where statements stretch multiple lines).
Nonetheless this will be implemented as soon as possible with an option to disable it as it may be distracting.

**Comment by chingucoding** [comment]
Wrong/faulty indentation is now being highlighted! :)
Sorry that this feature took that long.
