### ISSUE TITLE
Enhancement request: Different settings per language

### ISSUE THREAD

**Issue by Kurre** [chingucoding/IndentRainbow#8]
First of all, thanks for this great extension! 💯

Could it be possible to get settings per language? For example for C#, Javascript, etc.

In our current project C# uses 4 spaces indentation and JS files use 2 spaces indentation, so I wouldn't need to change it every time I change the task I'm working with.

Not a huge issue, but I'd welcome this kind of enhancement 👍

**Comment by chingucoding** [comment]
This is a very good idea! I'll try to get this done as soon as possible :)
